/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import vistas.ActualizacionDeNotas;

/**
 *
 * @author Marco
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        ImageIcon icono = new ImageIcon(getClass().getResource("/img/Fondo.png"));
        Image miImagen = icono.getImage();
        jDescritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(miImagen, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAlumno = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMMateria = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMAdministracion = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMConsultas = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión ULP");
        setName("principal"); // NOI18N

        javax.swing.GroupLayout jDescritorioLayout = new javax.swing.GroupLayout(jDescritorio);
        jDescritorio.setLayout(jDescritorioLayout);
        jDescritorioLayout.setHorizontalGroup(
            jDescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 987, Short.MAX_VALUE)
        );
        jDescritorioLayout.setVerticalGroup(
            jDescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(1, 68, 123));
        jMenuBar1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMAlumno.setBackground(new java.awt.Color(1, 68, 123));
        jMAlumno.setForeground(new java.awt.Color(255, 255, 255));
        jMAlumno.setText("Alumno");
        jMAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMAlumno.setFocusable(false);
        jMAlumno.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAlumnoActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Formulario de Alumno");
        jMAlumno.add(jMenuItem2);

        jMenuBar1.add(jMAlumno);

        jMMateria.setBackground(new java.awt.Color(1, 68, 123));
        jMMateria.setForeground(new java.awt.Color(255, 255, 255));
        jMMateria.setText("Materia");
        jMMateria.setFocusable(false);
        jMMateria.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem3.setText("Formulario de materia");
        jMMateria.add(jMenuItem3);

        jMenuBar1.add(jMMateria);

        jMAdministracion.setBackground(new java.awt.Color(1, 68, 123));
        jMAdministracion.setForeground(new java.awt.Color(255, 255, 255));
        jMAdministracion.setText("Administración");
        jMAdministracion.setFocusable(false);
        jMAdministracion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem4.setText("Manejo de inscripciones");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMAdministracion.add(jMenuItem4);

        jMenuItem5.setText("Manipulacion de notas");
        jMAdministracion.add(jMenuItem5);

        jMenuBar1.add(jMAdministracion);

        jMConsultas.setBackground(new java.awt.Color(1, 68, 123));
        jMConsultas.setForeground(new java.awt.Color(255, 255, 255));
        jMConsultas.setText("Consultas");
        jMConsultas.setFocusable(false);
        jMConsultas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem6.setText("Alumnos por materia");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMConsultas.add(jMenuItem6);

        jMenuBar1.add(jMConsultas);

        jMenu1.setBackground(new java.awt.Color(1, 68, 123));
        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Salir");
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("MenuPrincipal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDescritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDescritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
         
        jDescritorio.removeAll();
        jDescritorio.repaint();
        ActualizacionDeNotas nuevo = new ActualizacionDeNotas();
        nuevo.setVisible(true);
        jDescritorio.add(nuevo);
        jDescritorio.moveToFront(nuevo);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAlumnoActionPerformed
      
        jDescritorio.removeAll();
        jDescritorio.repaint();
        GestionDeAlumnos nuevo = new GestionDeAlumnos();
        nuevo.setVisible(true);
        jDescritorio.add(nuevo);
        jDescritorio.moveToFront(nuevo);
    }//GEN-LAST:event_jMAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDescritorio;
    private javax.swing.JMenu jMAdministracion;
    private javax.swing.JMenu jMAlumno;
    private javax.swing.JMenu jMConsultas;
    private javax.swing.JMenu jMMateria;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
}
