/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;



/**
 *
 * @author Marco
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        ImageIcon icono = new ImageIcon(getClass().getResource("/img/Fondo.png"));
        Image miImagen = icono.getImage();
        jDescritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(miImagen, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAlumno = new javax.swing.JMenu();
        jMalumno = new javax.swing.JMenuItem();
        jMMateria = new javax.swing.JMenu();
        jMmateria = new javax.swing.JMenuItem();
        jMInscripcion = new javax.swing.JMenu();
        jMinscripcion = new javax.swing.JMenuItem();
        jMmaniNotas = new javax.swing.JMenuItem();
        jMalumMateria = new javax.swing.JMenu();
        jMalumPorMateria = new javax.swing.JMenuItem();
        jMsalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión ULP");
        setName("principal"); // NOI18N

        javax.swing.GroupLayout jDescritorioLayout = new javax.swing.GroupLayout(jDescritorio);
        jDescritorio.setLayout(jDescritorioLayout);
        jDescritorioLayout.setHorizontalGroup(
            jDescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 987, Short.MAX_VALUE)
        );
        jDescritorioLayout.setVerticalGroup(
            jDescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(1, 68, 123));
        jMenuBar1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMAlumno.setBackground(new java.awt.Color(1, 68, 123));
        jMAlumno.setForeground(new java.awt.Color(255, 255, 255));
        jMAlumno.setText("Alumno");
        jMAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMAlumno.setFocusable(false);
        jMAlumno.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAlumnoActionPerformed(evt);
            }
        });

        jMalumno.setText("Formulario de Alumno");
        jMalumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMalumnoActionPerformed(evt);
            }
        });
        jMAlumno.add(jMalumno);

        jMenuBar1.add(jMAlumno);

        jMMateria.setBackground(new java.awt.Color(1, 68, 123));
        jMMateria.setForeground(new java.awt.Color(255, 255, 255));
        jMMateria.setText("Materia");
        jMMateria.setFocusable(false);
        jMMateria.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMMateriaActionPerformed(evt);
            }
        });

        jMmateria.setText("Formulario de materia");
        jMmateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmateriaActionPerformed(evt);
            }
        });
        jMMateria.add(jMmateria);

        jMenuBar1.add(jMMateria);

        jMInscripcion.setBackground(new java.awt.Color(1, 68, 123));
        jMInscripcion.setForeground(new java.awt.Color(255, 255, 255));
        jMInscripcion.setText("Administración");
        jMInscripcion.setFocusable(false);
        jMInscripcion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMinscripcion.setText("Manejo de inscripciones");
        jMinscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMinscripcionActionPerformed(evt);
            }
        });
        jMInscripcion.add(jMinscripcion);

        jMmaniNotas.setText("Manipulacion de notas");
        jMmaniNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmaniNotasActionPerformed(evt);
            }
        });
        jMInscripcion.add(jMmaniNotas);

        jMenuBar1.add(jMInscripcion);

        jMalumMateria.setBackground(new java.awt.Color(1, 68, 123));
        jMalumMateria.setForeground(new java.awt.Color(255, 255, 255));
        jMalumMateria.setText("Consultas");
        jMalumMateria.setFocusable(false);
        jMalumMateria.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMalumPorMateria.setText("Alumnos por materia");
        jMalumPorMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMalumPorMateriaActionPerformed(evt);
            }
        });
        jMalumMateria.add(jMalumPorMateria);

        jMenuBar1.add(jMalumMateria);

        jMsalir.setBackground(new java.awt.Color(1, 68, 123));
        jMsalir.setForeground(new java.awt.Color(255, 255, 255));
        jMsalir.setText("Salir");
        jMsalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuBar1.add(jMsalir);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("MenuPrincipal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDescritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDescritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMinscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMinscripcionActionPerformed
        // TODO add your handling code here:
        jDescritorio.removeAll();
        jDescritorio.repaint();
        Inscripciones in = new Inscripciones();
        in.setVisible(true);
        jDescritorio.add(in);
        jDescritorio.moveToFront(in);
    }//GEN-LAST:event_jMinscripcionActionPerformed

    private void jMalumPorMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMalumPorMateriaActionPerformed
    jDescritorio.removeAll();
        jDescritorio.repaint();
        AlumnosPorMateria nuevo = new AlumnosPorMateria();
        nuevo.setVisible(true);
        jDescritorio.add(nuevo);
        jDescritorio.moveToFront(nuevo);
    }//GEN-LAST:event_jMalumPorMateriaActionPerformed

    private void jMAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAlumnoActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_jMAlumnoActionPerformed

    private void jMMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMMateriaActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_jMMateriaActionPerformed

    private void jMmateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmateriaActionPerformed
           jDescritorio.removeAll();
        jDescritorio.repaint();
        GestionDeMaterias nuevo = new GestionDeMaterias();
        nuevo.setVisible(true);
        jDescritorio.add(nuevo);
        jDescritorio.moveToFront(nuevo);
    }//GEN-LAST:event_jMmateriaActionPerformed

    private void jMalumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMalumnoActionPerformed
   jDescritorio.removeAll();
        jDescritorio.repaint();
        GestionDeAlumnos ga = new GestionDeAlumnos();
        ga.setVisible(true);
        jDescritorio.add(ga);
        jDescritorio.moveToFront(ga);
    }//GEN-LAST:event_jMalumnoActionPerformed

    private void jMmaniNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmaniNotasActionPerformed
       jDescritorio.removeAll();
        jDescritorio.repaint();
        ActualizacionDeNotas ga = new ActualizacionDeNotas();
        ga.setVisible(true);
        jDescritorio.add(ga);
        jDescritorio.moveToFront(ga);
    }//GEN-LAST:event_jMmaniNotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDescritorio;
    private javax.swing.JMenu jMAlumno;
    private javax.swing.JMenu jMInscripcion;
    private javax.swing.JMenu jMMateria;
    private javax.swing.JMenu jMalumMateria;
    private javax.swing.JMenuItem jMalumPorMateria;
    private javax.swing.JMenuItem jMalumno;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMinscripcion;
    private javax.swing.JMenuItem jMmaniNotas;
    private javax.swing.JMenuItem jMmateria;
    private javax.swing.JMenu jMsalir;
    // End of variables declaration//GEN-END:variables
}
