/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import AccesoADatos.AlumnoData;
import AccesoADatos.InscripcionData;
import AccesoADatos.MateriaData;
import entidades.Alumno;
import entidades.Materia;
import entidades.Inscripcion;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristian
 */
public class Inscripciones extends javax.swing.JInternalFrame {

    private ArrayList<Materia> listaM;
    private ArrayList<Alumno> listaA;

    private InscripcionData inscData = new InscripcionData();
    private MateriaData mDAta = new MateriaData();
    private AlumnoData aData = new AlumnoData();

    DefaultTableModel tab = new DefaultTableModel();

    public Inscripciones() {
        
        
        initComponents();
        listaA = (ArrayList < Alumno >)aData.listarAlumnos();
        cargarAlumnos();
        armarCabecera();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTlistaInsc = new javax.swing.JTable();
        jBinscribir = new javax.swing.JButton();
        jBanuInsc = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCselecAlum = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jRmateInsc = new javax.swing.JRadioButton();
        jRmateNoInsc = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setTitle("Formulario de Inscripcion");
        setName(""); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jTlistaInsc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTlistaInsc);

        jBinscribir.setText("Inscribir");
        jBinscribir.setEnabled(false);
        jBinscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinscribirActionPerformed(evt);
            }
        });

        jBanuInsc.setText("Anular Inscripcion");
        jBanuInsc.setEnabled(false);
        jBanuInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBanuInscActionPerformed(evt);
            }
        });

        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Formulario de Inscripcion");

        jLabel2.setText("Seleccione un Alumno:");

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setText("Listado de Materias");

        jRmateInsc.setText("Materias Inscriptas");
        jRmateInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRmateInscActionPerformed(evt);
            }
        });

        jRmateNoInsc.setText("Materias No Inscriptas");
        jRmateNoInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRmateNoInscActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCselecAlum, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(150, 150, 150))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(19, 19, 19)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRmateInsc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRmateNoInsc)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBinscribir)
                        .addGap(70, 70, 70)
                        .addComponent(jBanuInsc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBsalir)
                        .addGap(36, 36, 36))))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCselecAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRmateInsc)
                    .addComponent(jRmateNoInsc))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBanuInsc)
                    .addComponent(jBinscribir)
                    .addComponent(jBsalir))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRmateInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRmateInscActionPerformed
        borrarFilas();
        jRmateNoInsc.setSelected(false);
        cargaDatosInscriptas();
        jBanuInsc.setEnabled(true);
        jBinscribir.setEnabled(false);


    }//GEN-LAST:event_jRmateInscActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jRmateNoInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRmateNoInscActionPerformed

        borrarFilas();
        jRmateInsc.setSelected(false);
        cargaDatosNoInscriptas();
        jBanuInsc.setEnabled(false);
        jBinscribir.setEnabled(true);
    }//GEN-LAST:event_jRmateNoInscActionPerformed

    private void jBinscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinscribirActionPerformed

        int filaSeleccionada = jTlistaInsc.getSelectedRow();
        if (filaSeleccionada != -1) {
            Alumno a = (Alumno) jCselecAlum.getSelectedItem();

            int idMateria = (Integer) tab.getValueAt(filaSeleccionada, 0);
            String nombreMateria = (String) tab.getValueAt(filaSeleccionada, 1);
            int anio = (Integer) tab.getValueAt(filaSeleccionada, 2);

            Materia m = new Materia(idMateria, nombreMateria, anio, true);

            Inscripcion i= new Inscripcion(); 
            inscData.guardarInscripcion(i);
            borrarFilas();

        }

    }//GEN-LAST:event_jBinscribirActionPerformed

    private void jBanuInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBanuInscActionPerformed
        int filaSeleccionada = jTlistaInsc.getSelectedRow();
          if (filaSeleccionada != -1) {
               Alumno a = (Alumno) jCselecAlum.getSelectedItem();
               
              int idMateria = (Integer) tab.getValueAt(filaSeleccionada, 0);
              
              inscData.borrarInscripcionMateriaAlumno(a.getIdAlumno(), idMateria);
              borrarFilas();
          }
        
        
    }//GEN-LAST:event_jBanuInscActionPerformed

    public void cargarAlumnos() {
        for (Alumno item :listaA) {
            jCselecAlum.addItem(item);
        }
    }

    public void armarCabecera() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("ID");
        filaCabecera.add("Nombre");
        filaCabecera.add("Año");

        for (Object it : filaCabecera) {
            tab.addColumn(it);
        }
        jTlistaInsc.setModel(tab);
    }

    private void borrarFilas() {
        int indice = tab.getRowCount() - 1;

        for (int i = indice; i >= 0; i--) {
            tab.removeRow(i);
        }
    }

    private void cargaDatosNoInscriptas() {
        Alumno selec = (Alumno) jCselecAlum.getSelectedItem();
        listaM =(ArrayList) inscData.obtenerMateriasNOCursadas(selec.getIdAlumno());
        for (Materia m : listaM) {
            tab.addRow(new Object[]{m.getIdMateria(), m.getNombre(), m.getAño()});
        }

    }

    private void cargaDatosInscriptas() {
        Alumno selec = (Alumno) jCselecAlum.getSelectedItem();
        listaM = (ArrayList)inscData.obtenerMateriasCursadas(selec.getIdAlumno());
        for (Materia m : listaM) {
            tab.addRow(new Object[]{m.getIdMateria(), m.getNombre(), m.getAño()});
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBanuInsc;
    private javax.swing.JButton jBinscribir;
    private javax.swing.JButton jBsalir;
    private javax.swing.JComboBox<Alumno> jCselecAlum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRmateInsc;
    private javax.swing.JRadioButton jRmateNoInsc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTlistaInsc;
    // End of variables declaration//GEN-END:variables
}
